version: "3.8"

services:
  drawingserver:
    image: drawingserver:latest # Replace with your actual image name and tag
    ports:
      - "8000:8000" # Assuming your server listens on port 8080. Adjust if needed.
    deploy:
      resources:
        limits:
          cpus: "0.25" # e2-micro has 0.25 vCPU
          memory: 1GiB # e2-micro has 1GB of RAM
    restart: unless-stopped